---

extends:
  - airbnb
  - "plugin:react/recommended"

parser: babel-eslint

env:
  node: true
  browser: true

rules:
  no-console: 0
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  react/jsx-filename-extension: 0
  no-trailing-spaces: 0
  no-restricted-globals: 0
  no-param-reassign: 0